# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mpdart(object):
    def setupUi(self, mpdart):
        mpdart.setObjectName("mpdart")
        mpdart.setWindowModality(QtCore.Qt.NonModal)
        mpdart.resize(420, 100)
        mpdart.setMinimumSize(QtCore.QSize(420, 100))
        mpdart.setMaximumSize(QtCore.QSize(420, 100))
        font = QtGui.QFont()
        font.setPointSize(6)
        mpdart.setFont(font)
        mpdart.setWindowOpacity(1.0)
        mpdart.setStyleSheet("background-color: rgb(29, 29, 29);\n"
"color: rgb(170, 255, 0);")
        self.track = QtWidgets.QLabel(mpdart)
        self.track.setGeometry(QtCore.QRect(11, 0, 308, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.track.setFont(font)
        self.track.setObjectName("track")
        self.album = QtWidgets.QLabel(mpdart)
        self.album.setGeometry(QtCore.QRect(11, 24, 308, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.album.setFont(font)
        self.album.setStyleSheet("color: rgb(85, 255, 255);")
        self.album.setObjectName("album")
        self.bitrate = QtWidgets.QLabel(mpdart)
        self.bitrate.setGeometry(QtCore.QRect(11, 42, 308, 11))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.bitrate.setFont(font)
        self.bitrate.setStyleSheet("color: rgb(255, 85, 255);")
        self.bitrate.setObjectName("bitrate")
        self.comment = QtWidgets.QLabel(mpdart)
        self.comment.setGeometry(QtCore.QRect(11, 53, 308, 28))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.comment.setFont(font)
        self.comment.setStyleSheet("color: rgb(255, 255, 0);")
        self.comment.setObjectName("comment")
        self.pbar = QtWidgets.QProgressBar(mpdart)
        self.pbar.setGeometry(QtCore.QRect(11, 83, 308, 5))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(5)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbar.setFont(font)
        self.pbar.setStyleSheet("font: 5pt \"Consolas\";")
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName("pbar")
        self.cdart = QtWidgets.QLabel(mpdart)
        self.cdart.setGeometry(QtCore.QRect(320, 4, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.cdart.setFont(font)
        self.cdart.setStyleSheet("background-color: rgb(74, 74, 74);")
        self.cdart.setAlignment(QtCore.Qt.AlignCenter)
        self.cdart.setObjectName("cdart")
        self.cb_top = QtWidgets.QCheckBox(mpdart)
        self.cb_top.setGeometry(QtCore.QRect(432, 4, 15, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_top.sizePolicy().hasHeightForWidth())
        self.cb_top.setSizePolicy(sizePolicy)
        self.cb_top.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.cb_top.setFont(font)
        self.cb_top.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_top.setIconSize(QtCore.QSize(8, 8))
        self.cb_top.setTristate(False)
        self.cb_top.setObjectName("cb_top")
        self.artist = QtWidgets.QLabel(mpdart)
        self.artist.setGeometry(QtCore.QRect(11, 12, 308, 16))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        font.setWeight(75)
        self.artist.setFont(font)
        self.artist.setStyleSheet("color: rgb(255, 170, 0);")
        self.artist.setObjectName("artist")

        self.retranslateUi(mpdart)
        QtCore.QMetaObject.connectSlotsByName(mpdart)

    def retranslateUi(self, mpdart):
        _translate = QtCore.QCoreApplication.translate
        mpdart.setWindowTitle(_translate("mpdart", "MPD-Art"))
        self.track.setText(_translate("mpdart", "track. title"))
        self.album.setText(_translate("mpdart", "album / albumartist (year)"))
        self.bitrate.setText(_translate("mpdart", "bitrate - publisher - encoding"))
        self.comment.setText(_translate("mpdart", "comment"))
        self.cdart.setText(_translate("mpdart", "CDArt"))
        self.cb_top.setText(_translate("mpdart", "CheckBox"))
        self.artist.setText(_translate("mpdart", "artist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mpdart = QtWidgets.QDialog()
    ui = Ui_mpdart()
    ui.setupUi(mpdart)
    mpdart.show()
    sys.exit(app.exec_())

